### ISSUE TITLE
Loading full /json every 2 seconds may be a bit too much?

### ISSUE THREAD

**Issue by TD-er** [chromoxdor/easyfetch#2] opened 2022-11-09 09:08 UTC
I have easyfetch running on a test node here. (looks amazing :) )

On this board, I have an external RTC chip.
So I do see these logentries continuously:

```
2558721 : Info   : ExtRTC: Read external time source: 1667984668
2560734 : Info   : ExtRTC: Read external time source: 1667984670
```

Of course, I could (should?) put this log into LOG_LEVEL_DEBUG.
But the reason I'm seeing this is because the full json is loaded every time.

So I'm wondering if you need to read the full json every time, or maybe you could load the sensorupdate all the time and the full json every N calls?
See: https://espeasy.readthedocs.io/en/latest/Reference/URLs.html?highlight=json#json

Or will that break something?

**Comment by chromoxdor** [comment] 2022-11-09 12:10
This project was my first time where i ever used javascript and i haven’t touched the core function for quite a while.
The problem is when you don’t repeat what you learn you will forget the knowledge over time.😬
So let me see if i still understand what i wrote... 😁

I guess i load the whole json because of the node infos and the wifi-strength. But i remember that i always wantet to make the tile refesh based on the "TTL"  value assuming this represents is the shortest interval of a device in the devices section.

> So I do see these logentries continuously:

Is this because a json request triggers a read of an external RTC? (and therefore a logentry)

> Or will that break something?

We will see. 🙂

**Comment by TD-er** [comment] 2022-11-09 12:22
> Is this because a json request triggers a read of an external RTC? (and therefore a logentry)
> 

Yep :)

**Comment by chromoxdor** [comment] 2022-11-09 13:12
I just looked at the code...
Is the external RTC the only reason why it shouldn’t read the full json every time? (It would need a lot of changes, only to get rid of the logentry of the RTC )
If so... 

> Of course, I could (should?) put this log into LOG_LEVEL_DEBUG.

..you should :)

**Comment by TD-er** [comment] 2022-11-09 13:15
Nope, that's not the only reason, but is more like an indicator of what's happening.

I'm just a bit concerned about the possible load it may give while serving larger JSON may give a bit more load on the ESP resources.
So I was wondering if it could be done more efficient.

**Comment by chromoxdor** [comment] 2022-11-09 13:23
I did some amateurish testing about load with an esp8266 which was already doing a lot work a while ago. I couldn’t see any issues and no significant increase of load or slowdown. 
I also have a lot of devices that run easyfetch or at least where i testet it and i never run across any issues.
But thats only me. 
So i would like to leave it as it is until issues of other user appear.  What i  will change is the 2 seconds reload to a TTL dependent reload.

**Comment by TD-er** [comment] 2022-11-09 13:34
> What i will change is the 2 seconds reload to a TTL dependent reload.

I think that will already make it much more dynamic and sounds "good enough" to me. :)

**Comment by haldi4803** [comment] 2022-11-09 13:41
Ahhhh. So thats why!
I was using F12 Button in Firefox to select the button but it got reset every 2 seconds. Kinda annoying^^

**Comment by TD-er** [comment] 2022-11-09 13:44
> Ahhhh. So thats why! I was using F12 Button in Firefox to select the button but it got reset every 2 seconds. Kinda annoying^^

Just curious, what does this do in Firefox?

**Comment by haldi4803** [comment] 2022-11-09 13:45
Same as on Chrome i assume, check out Page settings and css.
![image](https://user-images.githubusercontent.com/17104473/200846283-c99891c7-d84c-4dd6-afc8-ce639fb91f37.png)

**Comment by chromoxdor** [comment] 2022-11-09 14:28
for inspecting the page with the developer tools you need to disable javascript.
The content is redrawn every two seconds....

**Comment by chromoxdor** [comment] 2022-11-09 15:20
> > What i will change is the 2 seconds reload to a TTL dependent reload.

> 
> I think that will already make it much more dynamic and sounds "good enough" to me. :)

@TD-er
Now i remember why i didn´t follow this approach. 
Usually when you press a virtual button, easyfetch makes a json request shortly after this event with a short delay (400ms) to give an immediate response to the button change (e.g. button turning blue).
But it can happen, that due to network issues, the state change happens after the new json request.
Therefore the 2sec interval is also a fallback for these occasions.
Imagine now a TTL of 60sec. The response could come worst case 60secs later....

I could increase the delay of the new request a bit...but a button press wouldn´t feel responsive enough and also it  wouldn’t cover all the occasions where the change comes after the request....
Maybe i find another option.
Ideas are welcome.....

**Comment by TD-er** [comment] 2022-11-09 15:31
OK, makes sense.

Maybe you could make the interval a bit more dynamic.
Like increase the interval depending on the last interaction, upto the TTL (or half the TTL)

Well, it isn't such a big deal, but I was just wondering if this was really needed.

One other thing to keep in mind is that periodical requests like these may prevent the ESP from entering the lower power mode like the "ECO" mode does.
This can be a good and a bad thing. 
Good as in the ESP will remain responsive.
Bad as in the ESP may never enter a low(er) power state.

**Comment by chromoxdor** [comment] 2022-11-09 15:42
> One other thing to keep in mind is that periodical requests like these may prevent the ESP from entering the lower power

True, but usually you open the page hit a button and close it. So no more request unless you use it as a display.
For displaying things constantly, i have a "mainunit" sending events to the other nodes and these nodes send their state back via `sendto`

Here the "main" easyfetch device:
<img width="445" alt="Bildschirmfoto 2022-11-09 um 16 37 32" src="https://user-images.githubusercontent.com/33860956/200874205-efae8110-f223-430c-8165-0dc833762919.png">

And here the Rules code of a node which sends constantly its state:
```
On Rules#Timer=2 Do
  SendTo,1,TaskValueSet,3,1,[Relay#btnState]
Endon
```

**Comment by chromoxdor** [comment] 2022-11-09 15:46
> Like increase the interval depending on the last interaction, upto the TTL (or half the TTL)

Thats actually a good idea... i´ll look into that.

**Comment by chromoxdor** [comment] 2022-12-03 14:07
@TD-er I'm working on the TTL dependent update right now, but it seems that all nodes always have 1000ms as TTL no matter what I do. The only exception is a node with firmware prior to 2022.... Did I miss a setting somewhere else? As I understand it, it's only set after the smallest interval in the devices section.

**Comment by TD-er** [comment] 2022-12-03 16:08
I have changed it to 1000 msec a while ago as it was asked a bit too often why the device page wasn't updating...
Only to have forgotten myself I changed it ;)

**Comment by chromoxdor** [comment] 2022-12-03 16:50
And now you want the people to ask me why the Dashboard isn´t updating. 😁

**Comment by TD-er** [comment] 2022-12-03 20:27
> And now you want the people to ask me why the Dashboard isn´t updating. 😁

I knew you would understand ;)

**Comment by chromoxdor** [comment] 2024-01-23 19:16
Intensive hours of testing and no complaints...It seems that a 2 seconds interval is fine....
Issue closed :)

**Closed as completed** 2024-01-23 19:17 UTC
